#!/usr/bin/env python3
"""Regenerates src/UnicodeTables.inc, the two Unicode tables behind
src/UnicodeText.cpp: simple uppercase mappings and "alphanumeric" code points.

Why these exist (docs/OPEN_ITEMS.md, series-rule title matching): Dispatcharr
matches a series rule's title against programme titles in PostgreSQL --
`title__iexact` compiles to `UPPER(title) = UPPER(value)` and `icontains` to
`UPPER(title) LIKE UPPER('%value%')` -- and on a libc-collation database
(the stock Debian-based postgres image) `UPPER()` is glibc's `towupper()`
applied one code point at a time, while a whole-word match's `\\y` boundary
treats `iswalnum()` code points as word characters. This addon's own
ToLower() only folds ASCII, so a rule whose title differs from its
programmes' only in non-ASCII letter case never linked back to them.
Confirmed live that the real instance's database does fold non-ASCII case
(an `icontains` for "ünder" matched a channel named "ÜNDER"), so the tables
are generated from glibc's own functions rather than Python's `str.upper()`,
which differs in exactly the places that matter here: Python's uppercase
mapping is the *full* one (U+00DF sharp s becomes "SS", U+1F80 becomes two
code points), so a single-code-point filter would drop the 27 Greek letters
with prosgegrammeni that glibc maps to their titlecase forms, and Python's
`isalnum()` disagrees with glibc's `iswalnum()` on a couple of thousand
code points.

Usage (Linux with glibc only; the output is committed, nothing builds from
this script):
  python3 tools/gen_unicode_tables.py            # rewrite src/UnicodeTables.inc
  python3 tools/gen_unicode_tables.py --check    # exit 1 if the committed file is stale
"""

import ctypes
import ctypes.util
import sys
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent / "src" / "UnicodeTables.inc"
LC_CTYPE = 0  # glibc's value; this script is Linux-only by design
MAX_CODE_POINT = 0x10FFFF


def load_libc():
    path = ctypes.util.find_library("c")
    if not path:
        sys.exit("gen_unicode_tables: libc not found (this needs glibc)")
    libc = ctypes.CDLL(path)
    libc.gnu_get_libc_version.restype = ctypes.c_char_p
    libc.setlocale.restype = ctypes.c_char_p
    libc.setlocale.argtypes = [ctypes.c_int, ctypes.c_char_p]
    if libc.setlocale(LC_CTYPE, b"C.UTF-8") is None:
        sys.exit("gen_unicode_tables: the C.UTF-8 locale isn't available (glibc >= 2.35 has it built in)")
    libc.towupper.argtypes = [ctypes.c_uint]
    libc.towupper.restype = ctypes.c_uint
    libc.iswalnum.argtypes = [ctypes.c_uint]
    libc.iswalnum.restype = ctypes.c_int
    return libc


def build_upper_ranges(libc):
    """(first, last, delta, stride) runs covering every code point >= 0x80 whose towupper() differs from itself.
    A stride of 2 covers the many Latin/Greek/Cyrillic blocks where only every other code point has a mapping
    (lowercase at the odd positions, uppercase at the even ones)."""
    pairs = []
    for c in range(0x80, MAX_CODE_POINT + 1):
        if 0xD800 <= c <= 0xDFFF:
            continue
        u = libc.towupper(c)
        if u != c:
            pairs.append((c, u - c))
    ranges = []
    i = 0
    while i < len(pairs):
        first, delta = pairs[i]
        last = first
        stride = 1
        j = i + 1
        if j < len(pairs) and pairs[j][1] == delta and pairs[j][0] - first in (1, 2):
            stride = pairs[j][0] - first
        while j < len(pairs) and pairs[j][1] == delta and pairs[j][0] == last + stride:
            last = pairs[j][0]
            j += 1
        ranges.append((first, last, delta, stride))
        i = j
    return ranges, len(pairs)


def build_alnum_ranges(libc):
    ranges = []
    start = None
    prev = None
    for c in range(0x80, MAX_CODE_POINT + 1):
        is_alnum = not (0xD800 <= c <= 0xDFFF) and bool(libc.iswalnum(c))
        if is_alnum:
            if start is None:
                start = c
            prev = c
        elif start is not None:
            ranges.append((start, prev))
            start = None
    if start is not None:
        ranges.append((start, prev))
    return ranges


def render(libc):
    upper_ranges, mapped = build_upper_ranges(libc)
    alnum_ranges = build_alnum_ranges(libc)
    glibc_version = libc.gnu_get_libc_version().decode()
    lines = [
        "// GENERATED by tools/gen_unicode_tables.py -- do not edit by hand.",
        f"// Source: glibc {glibc_version}'s C.UTF-8 towupper() and iswalnum(), the functions PostgreSQL's",
        "// UPPER() and regex word-boundary (\\y) use on a libc-collation database. See that script's own",
        "// docstring for why these are not Python's str.upper()/isalnum().",
        f"// {mapped} code points have a simple uppercase mapping above U+007F, in {len(upper_ranges)} ranges;",
        f"// {len(alnum_ranges)} ranges of alphanumeric code points above U+007F.",
        "",
        "// {first, last, delta, stride}: every code point c in [first, last], stepping by `stride`,",
        "// maps to c + delta.",
        "constexpr UpperRange kUpperRanges[] = {",
    ]
    for first, last, delta, stride in upper_ranges:
        lines.append(f"    {{0x{first:04X}, 0x{last:04X}, {delta}, {stride}}},")
    lines += [
        "};",
        "",
        "// {first, last}: every code point in [first, last] is alphanumeric.",
        "constexpr CodePointRange kAlnumRanges[] = {",
    ]
    for first, last in alnum_ranges:
        lines.append(f"    {{0x{first:04X}, 0x{last:04X}}},")
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    libc = load_libc()
    text = render(libc)
    if "--check" in sys.argv[1:]:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != text:
            print(f"gen_unicode_tables: {OUTPUT.name} is stale -- rerun this script", file=sys.stderr)
            return 1
        print(f"gen_unicode_tables: {OUTPUT.name} is up to date")
        return 0
    OUTPUT.write_text(text)
    print(f"gen_unicode_tables: wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
